### ISSUE TITLE
python3?

### ISSUE THREAD

**Issue by MadHobbs** [sylvia-dee/PRYSM#10]
Hi! Is PRYSM compatible with python 3? Thanks!

**Comment by sylvia-dee** [comment]
Hi there MadHobbs! Sorry for the delay in my response, I was in the middle of moving cross-country :)

Unfortunately there are some minor incompatibilities, but on the whole the scripts should run and are primarily just using basic numpy and scipy libraries. If you have problems, you can try this conversion tool: https://docs.python.org/3/library/2to3.html

Another option is to pull the scripts for the PSMs you want to use directly and modify as needed. Let me know if I can help!

**Comment by sylvia-dee** [comment]
Hello! I have finally merged @brandonmburroughs pull request and PRYSM should now be fully operational in Python3. Thanks again!
