### ISSUE TITLE
'bool' object is not iterable

### ISSUE THREAD

**Issue by alanabspaetzel** [sylvia-dee/PRYSM#6]
I am running the coral PSM in Python and I keep getting an error with lines 69-72 saying

TypeError                                 Traceback (most recent call last)
C:\Users\Alana\Desktop\PRYSM-master\examples\coral_driver.py in <module>()
     68 
     69 # longitude
---> 70 lon_flag = any(lon<0.)
     71 for i in range(len(lon)):
     72     if (lon_flag):

TypeError: 'bool' object is not iterable

**Comment by sylvia-dee** [comment]
Hi Alana,
Try switching the order of lines 71 and 72.

Aka:

if (lon_flag):
    for i in range(len(lon)):
         <change longitude grid>

Let me know if that works! Sorry for the delay.

**Comment by sylvia-dee** [comment]
Alana, I've updated the code in coral_driver.py, simplifying it. The (any) function doesn't work in this context. Thank you so much for pointing out the bug! Try re-downloading that script or running line by line in iPython to see if it will work for you. Let me know if you have more problems.

**Comment by alanabspaetzel** [comment]
Thanks so much, Sylvia!
